clone_depth: 1
# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

# Install scripts. (runs after repo cloning)
install:
  # Install the version of nodejs specified in the matrix
  - ps: Install-Product node $env:nodejs_version
  # link pipetree so we can execute httpsget
  #- npm link
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
